### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by GeorgeKaspar** [ulikoehler/cv_algorithms#1]
pip install git+https://github.com/ulikoehler/cv_algorithms.git

(py36) george@george-OMEN-by-HP-Laptop ~/KasparNet $ pip install git+https://github.com/ulikoehler/cv_algorithms.git
Collecting git+https://github.com/ulikoehler/cv_algorithms.git
  Cloning https://github.com/ulikoehler/cv_algorithms.git to /tmp/pip-req-build-n4uiz7sw
Requirement already satisfied: cffi>=0.7 in /home/george/anaconda3/envs/py36/lib/python3.6/site-packages (from cv-algorithms==1.0.0) (1.11.4)
Requirement already satisfied: pycparser in /home/george/anaconda3/envs/py36/lib/python3.6/site-packages (from cffi>=0.7->cv-algorithms==1.0.0) (2.18)
Building wheels for collected packages: cv-algorithms
  Running setup.py bdist_wheel for cv-algorithms ... error
  Complete output from command /home/george/anaconda3/envs/py36/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-n4uiz7sw/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-ekl475_a --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/test
  copying test/__init__.py -> build/lib.linux-x86_64-3.6/test
  copying test/TestContours.py -> build/lib.linux-x86_64-3.6/test
  copying test/TestUtils.py -> build/lib.linux-x86_64-3.6/test
  copying test/TestThinning.py -> build/lib.linux-x86_64-3.6/test
  copying test/TestNeighbours.py -> build/lib.linux-x86_64-3.6/test
  copying test/TestDistance.py -> build/lib.linux-x86_64-3.6/test
  copying test/TestColorspace.py -> build/lib.linux-x86_64-3.6/test
  copying test/TestGrassfire.py -> build/lib.linux-x86_64-3.6/test
  copying test/TestPopcount.py -> build/lib.linux-x86_64-3.6/test
  creating build/lib.linux-x86_64-3.6/cv_algorithms
  copying cv_algorithms/__init__.py -> build/lib.linux-x86_64-3.6/cv_algorithms
  copying cv_algorithms/grassfire.py -> build/lib.linux-x86_64-3.6/cv_algorithms
  copying cv_algorithms/text.py -> build/lib.linux-x86_64-3.6/cv_algorithms
  copying cv_algorithms/_ffi.py -> build/lib.linux-x86_64-3.6/cv_algorithms
  copying cv_algorithms/contours.py -> build/lib.linux-x86_64-3.6/cv_algorithms
  copying cv_algorithms/popcount.py -> build/lib.linux-x86_64-3.6/cv_algorithms
  copying cv_algorithms/colorspace.py -> build/lib.linux-x86_64-3.6/cv_algorithms
  copying cv_algorithms/distance.py -> build/lib.linux-x86_64-3.6/cv_algorithms
  copying cv_algorithms/morphology.py -> build/lib.linux-x86_64-3.6/cv_algorithms
  copying cv_algorithms/classification.py -> build/lib.linux-x86_64-3.6/cv_algorithms
  copying cv_algorithms/thinning.py -> build/lib.linux-x86_64-3.6/cv_algorithms
  copying cv_algorithms/_checks.py -> build/lib.linux-x86_64-3.6/cv_algorithms
  copying cv_algorithms/neighbours.py -> build/lib.linux-x86_64-3.6/cv_algorithms
  copying cv_algorithms/utils.py -> build/lib.linux-x86_64-3.6/cv_algorithms
  running build_ext
  building 'cv_algorithms._cv_algorithms' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/src
  gcc -pthread -B /home/george/anaconda3/envs/py36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/george/anaconda3/envs/py36/include/python3.6m -c src/thinning.cpp -o build/temp.linux-x86_64-3.6/src/thinning.o -g -O2 -march=native
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  gcc -pthread -B /home/george/anaconda3/envs/py36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/george/anaconda3/envs/py36/include/python3.6m -c src/distance.cpp -o build/temp.linux-x86_64-3.6/src/distance.o -g -O2 -march=native
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  src/distance.cpp: In function ‘int pairwise_diff(const double*, const double*, double*, size_t, size_t)’:
  src/distance.cpp:18:46: error: call of overloaded ‘abs(double)’ is ambiguous
      result[ax*awidth + bx] = abs(a[ax] - b[bx]);
                                                ^
  In file included from /usr/include/c++/6/cstdlib:75:0,
                   from /usr/include/c++/6/stdlib.h:36,
                   from src/distance.cpp:1:
  /usr/include/stdlib.h:774:12: note: candidate: int abs(int)
   extern int abs (int __x) __THROW __attribute__ ((__const__)) __wur;
              ^~~
  In file included from /usr/include/c++/6/stdlib.h:36:0,
                   from src/distance.cpp:1:
  /usr/include/c++/6/cstdlib:185:3: note: candidate: __int128 std::abs(__int128)
     abs(__GLIBCXX_TYPE_INT_N_0 __x) { return __x >= 0 ? __x : -__x; }
     ^~~
  /usr/include/c++/6/cstdlib:180:3: note: candidate: long long int std::abs(long long int)
     abs(long long __x) { return __builtin_llabs (__x); }
     ^~~
  /usr/include/c++/6/cstdlib:172:3: note: candidate: long int std::abs(long int)
     abs(long __i) { return __builtin_labs(__i); }
     ^~~
  error: command 'gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for cv-algorithms
  Running setup.py clean for cv-algorithms
Failed to build cv-algorithms
Installing collected packages: cv-algorithms
  Running setup.py install for cv-algorithms ... error
    Complete output from command /home/george/anaconda3/envs/py36/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-n4uiz7sw/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-i4nvkxyk/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/test
    copying test/__init__.py -> build/lib.linux-x86_64-3.6/test
    copying test/TestContours.py -> build/lib.linux-x86_64-3.6/test
    copying test/TestUtils.py -> build/lib.linux-x86_64-3.6/test
    copying test/TestThinning.py -> build/lib.linux-x86_64-3.6/test
    copying test/TestNeighbours.py -> build/lib.linux-x86_64-3.6/test
    copying test/TestDistance.py -> build/lib.linux-x86_64-3.6/test
    copying test/TestColorspace.py -> build/lib.linux-x86_64-3.6/test
    copying test/TestGrassfire.py -> build/lib.linux-x86_64-3.6/test
    copying test/TestPopcount.py -> build/lib.linux-x86_64-3.6/test
    creating build/lib.linux-x86_64-3.6/cv_algorithms
    copying cv_algorithms/__init__.py -> build/lib.linux-x86_64-3.6/cv_algorithms
    copying cv_algorithms/grassfire.py -> build/lib.linux-x86_64-3.6/cv_algorithms
    copying cv_algorithms/text.py -> build/lib.linux-x86_64-3.6/cv_algorithms
    copying cv_algorithms/_ffi.py -> build/lib.linux-x86_64-3.6/cv_algorithms
    copying cv_algorithms/contours.py -> build/lib.linux-x86_64-3.6/cv_algorithms
    copying cv_algorithms/popcount.py -> build/lib.linux-x86_64-3.6/cv_algorithms
    copying cv_algorithms/colorspace.py -> build/lib.linux-x86_64-3.6/cv_algorithms
    copying cv_algorithms/distance.py -> build/lib.linux-x86_64-3.6/cv_algorithms
    copying cv_algorithms/morphology.py -> build/lib.linux-x86_64-3.6/cv_algorithms
    copying cv_algorithms/classification.py -> build/lib.linux-x86_64-3.6/cv_algorithms
    copying cv_algorithms/thinning.py -> build/lib.linux-x86_64-3.6/cv_algorithms
    copying cv_algorithms/_checks.py -> build/lib.linux-x86_64-3.6/cv_algorithms
    copying cv_algorithms/neighbours.py -> build/lib.linux-x86_64-3.6/cv_algorithms
    copying cv_algorithms/utils.py -> build/lib.linux-x86_64-3.6/cv_algorithms
    running build_ext
    building 'cv_algorithms._cv_algorithms' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    gcc -pthread -B /home/george/anaconda3/envs/py36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/george/anaconda3/envs/py36/include/python3.6m -c src/thinning.cpp -o build/temp.linux-x86_64-3.6/src/thinning.o -g -O2 -march=native
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    gcc -pthread -B /home/george/anaconda3/envs/py36/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/george/anaconda3/envs/py36/include/python3.6m -c src/distance.cpp -o build/temp.linux-x86_64-3.6/src/distance.o -g -O2 -march=native
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    src/distance.cpp: In function ‘int pairwise_diff(const double*, const double*, double*, size_t, size_t)’:
    src/distance.cpp:18:46: error: call of overloaded ‘abs(double)’ is ambiguous
        result[ax*awidth + bx] = abs(a[ax] - b[bx]);
                                                  ^
    In file included from /usr/include/c++/6/cstdlib:75:0,
                     from /usr/include/c++/6/stdlib.h:36,
                     from src/distance.cpp:1:
    /usr/include/stdlib.h:774:12: note: candidate: int abs(int)
     extern int abs (int __x) __THROW __attribute__ ((__const__)) __wur;
                ^~~
    In file included from /usr/include/c++/6/stdlib.h:36:0,
                     from src/distance.cpp:1:
    /usr/include/c++/6/cstdlib:185:3: note: candidate: __int128 std::abs(__int128)
       abs(__GLIBCXX_TYPE_INT_N_0 __x) { return __x >= 0 ? __x : -__x; }
       ^~~
    /usr/include/c++/6/cstdlib:180:3: note: candidate: long long int std::abs(long long int)
       abs(long long __x) { return __builtin_llabs (__x); }
       ^~~
    /usr/include/c++/6/cstdlib:172:3: note: candidate: long int std::abs(long int)
       abs(long __i) { return __builtin_labs(__i); }
       ^~~
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/home/george/anaconda3/envs/py36/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-n4uiz7sw/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-i4nvkxyk/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-n4uiz7sw/
(py36) george@george-OMEN-by-HP-Laptop ~/KasparNet $

**Comment by ulikoehler** [comment]
Thanks for reporting this!
The issue seems to be

```
src/distance.cpp:18:46: error: call of overloaded ‘abs(double)’ is ambiguous
result[ax*awidth + bx] = abs(a[ax] - b[bx]);
```
however I can't reproduce this on Ubuntu 18.04. I believe it is either caused by a different version of GCC or a different version of some library.

Could you share the following information?
1. Output of `gcc -v`
2. Which distribution & version of that distribution you are using (e.g. "Debian Jessie")?

I'm convinced it's a pretty easy fix, but I need to be able to reproduce it somehow.

**Comment by DELTA37** [comment]
george@george-OMEN-by-HP-Laptop ~/aramco_hack $ lsb_release -cd
Description:	Linux Mint 18.3 Sylvia
Codename:	sylvia
george@george-OMEN-by-HP-Laptop ~/aramco_hack $ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 6.4.0-17ubuntu1~16.04' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --with-as=/usr/bin/x86_64-linux-gnu-as --with-ld=/usr/bin/x86_64-linux-gnu-ld --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.4.0 20180424 (Ubuntu 6.4.0-17ubuntu1~16.04) 
george@george-OMEN-by-HP-Laptop ~/aramco_hack $

**Comment by mekacharan** [comment]
Hi I am also facing the same issue in windoiws.
 C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\lenovo\appdata\local\programs\python\python36\include -Ic:\users\lenovo\appdata\local\programs\python\python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /EHsc /Tpsrc/distance.cpp /Fobuild\temp.win-amd64-3.6\Release\src/distance.obj -g -O2 -march=native
    cl : Command line warning D9002 : ignoring unknown option '-g'
    cl : Command line warning D9002 : ignoring unknown option '-march=native'
    distance.cpp
    src/distance.cpp(18): error C2668: 'abs': ambiguous call to overloaded function
    C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\stdlib.h(364): note: could be '__int64 abs(const __int64) throw()'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\stdlib.h(359): note: or       'long abs(const long) throw()'
    C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\stdlib.h(289): note: or       'int abs(int)'
    src/distance.cpp(18): note: while trying to match the argument list '(double)'
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Comment by ulikoehler** [comment]
@mekacharan  @GeorgeKaspar I've added an explicit cast to `int64_t` to try to resolve this issue. Can you retry the `pip install` command (if you cloned the repository instead of using `git+https://...` with `pip`, you might need to `git pull` before that)?

**Comment by mekacharan** [comment]
Hi Thanks for the prompt support.

When I tried installing i am getting this error 
 src/popcount.cpp(20): error C3861: '__builtin_popcount': identifier not found
    src/popcount.cpp(27): error C3861: '__builtin_popcount': identifier not found
    src/popcount.cpp(34): error C3861: '__builtin_popcount': identifier not found
    src/popcount.cpp(41): error C3861: '__builtin_popcountll': identifier not found
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.15.26726\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Comment by vendilhao** [comment]
> 
> 
> Hi Thanks for the prompt support.
> 
> When I tried installing i am getting this error
> src/popcount.cpp(20): error C3861: '__builtin_popcount': identifier not found
> src/popcount.cpp(27): error C3861: '__builtin_popcount': identifier not found
> src/popcount.cpp(34): error C3861: '__builtin_popcount': identifier not found
> src/popcount.cpp(41): error C3861: '__builtin_popcountll': identifier not found
> error: command 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.15.26726\bin\HostX86\x64\cl.exe' failed with exit status 2

Same here :/

**Comment by vtatntpt** [comment]
Same issue on windows 10

Running setup.py install for cv-algorithms ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-req-build-3pacc019\\setup.py'"'"'; __file__='"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-req-build-3pacc019\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Admin\AppData\Local\Temp\pip-record-peg_4hry\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\Admin\AppData\Local\Temp\pip-req-build-3pacc019\
    Complete output (41 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\cv_algorithms
    copying cv_algorithms\classification.py -> build\lib.win-amd64-3.7\cv_algorithms
    copying cv_algorithms\colorspace.py -> build\lib.win-amd64-3.7\cv_algorithms
    copying cv_algorithms\contours.py -> build\lib.win-amd64-3.7\cv_algorithms
    copying cv_algorithms\distance.py -> build\lib.win-amd64-3.7\cv_algorithms
    copying cv_algorithms\grassfire.py -> build\lib.win-amd64-3.7\cv_algorithms
    copying cv_algorithms\morphology.py -> build\lib.win-amd64-3.7\cv_algorithms
    copying cv_algorithms\neighbours.py -> build\lib.win-amd64-3.7\cv_algorithms
    copying cv_algorithms\popcount.py -> build\lib.win-amd64-3.7\cv_algorithms
    copying cv_algorithms\text.py -> build\lib.win-amd64-3.7\cv_algorithms
    copying cv_algorithms\thinning.py -> build\lib.win-amd64-3.7\cv_algorithms
    copying cv_algorithms\utils.py -> build\lib.win-amd64-3.7\cv_algorithms
    copying cv_algorithms\_checks.py -> build\lib.win-amd64-3.7\cv_algorithms
    copying cv_algorithms\_ffi.py -> build\lib.win-amd64-3.7\cv_algorithms
    copying cv_algorithms\__init__.py -> build\lib.win-amd64-3.7\cv_algorithms
    creating build\lib.win-amd64-3.7\test
    copying test\TestColorspace.py -> build\lib.win-amd64-3.7\test
    copying test\TestContours.py -> build\lib.win-amd64-3.7\test
    copying test\TestDistance.py -> build\lib.win-amd64-3.7\test
    copying test\TestGrassfire.py -> build\lib.win-amd64-3.7\test
    copying test\TestNeighbours.py -> build\lib.win-amd64-3.7\test
    copying test\TestPopcount.py -> build\lib.win-amd64-3.7\test
    copying test\TestThinning.py -> build\lib.win-amd64-3.7\test
    copying test\TestUtils.py -> build\lib.win-amd64-3.7\test
    copying test\__init__.py -> build\lib.win-amd64-3.7\test
    running build_ext
    building 'cv_algorithms._cv_algorithms' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\src
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.22.27905\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT "-Ic:\program files\python37\include" "-Ic:\program files\python37\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.22.27905\include" /EHsc /Tpsrc/thinning.cpp /Fobuild\temp.win-amd64-3.7\Release\src/thinning.obj -g -O2 -march=native
    cl : Command line warning D9002 : ignoring unknown option '-g'
    cl : Command line warning D9002 : ignoring unknown option '-march=native'
    thinning.cpp
    src/thinning.cpp(1): fatal error C1083: Cannot open include file: 'stdlib.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files\python37\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-req-build-3pacc019\\setup.py'"'"'; __file__='"'"'C:\\Users\\Admin\\AppData\\Local\\Temp\\pip-req-build-3pacc019\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Admin\AppData\Local\Temp\pip-record-peg_4hry\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by ulikoehler** [comment]
@vtatntpt
Your issue seems to be different. You are missing stdlib.h - I recommend to Google for "msvcc stdlib.h not found" and try out some of the solutions suggested there. It's not specifically an issue with cv_algorithms, however maybe if you could share what worked for you we might be able to provide that solutions to other users

**Comment by ulikoehler** [comment]
@others
Although I couldn't spend any time on the popcount issue before, I am still aware of it and will try to find a solution.

**Comment by ulikoehler** [comment]
@mekacharan  @vendilhao 
Based on https://stackoverflow.com/a/24550632/2597135 I have implemented a solution for Microsoft compilers.

Could you check on your platform?

**Comment by CrazyCrud** [comment]
> @mekacharan @vendilhao
> Based on https://stackoverflow.com/a/24550632/2597135 I have implemented a solution for Microsoft compilers.
> 
> Could you check on your platform?

Unfortunately, the error message is still the same:
`
src/popcount.cpp(46): error C3861: "__builtin_popcountll": Bezeichner wurde nicht gefunden.
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
`

**Comment by ulikoehler** [comment]
@CrazyCrud Thanks for checking.This seems to be a different error message. Now it's complaining about `__builtin_popcountll` (long long version).

I have just commited a possible fix, could you try again?

**Comment by CrazyCrud** [comment]
@ulikoehler No problem.
I tried to install it with the new fix, but another error occured:
`
LINK : error LNK2001: Nicht aufgelöstes externes Symbol "PyInit__cv_algorithms".
    build\temp.win-amd64-3.6\Release\src\_cv_algorithms.cp36-win_amd64.lib : fatal error LNK1120: 1 nicht aufgelöste Externe
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\link.exe' failed with exit status 1120
`
You can see the full log is [here](https://github.com/ulikoehler/cv_algorithms/files/3761573/log.txt).

**Comment by fducau** [comment]
> @ulikoehler No problem.
> I tried to install it with the new fix, but another error occured:
> `LINK : error LNK2001: Nicht aufgelöstes externes Symbol "PyInit__cv_algorithms". build\temp.win-amd64-3.6\Release\src\_cv_algorithms.cp36-win_amd64.lib : fatal error LNK1120: 1 nicht aufgelöste Externe error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\link.exe' failed with exit status 1120`
> You can see the full log is [here](https://github.com/ulikoehler/cv_algorithms/files/3761573/log.txt).

This one seems related with #4

**Comment by ulikoehler** [comment]
I've just released a fix for the Windows installation problem, could you please check if the issue persists?
